/**
 * Bundled Device Images Manifest
 *
 * Maps device slugs to bundled WebP images using Vite's static asset imports.
 * These images are pre-bundled with the app for immediate display.
 *
 * Images sourced from NetBox Device Type Library (CC0 licensed)
 * https://github.com/netbox-community/devicetype-library
 */

// Server images
import server1uFront from '$lib/assets/device-images/server/1u-server.front.webp';
import server2uFront from '$lib/assets/device-images/server/2u-server.front.webp';
import server4uFront from '$lib/assets/device-images/server/4u-server.front.webp';

// Network images
import switch8portFront from '$lib/assets/device-images/network/8-port-switch.front.webp';
import switch24portFront from '$lib/assets/device-images/network/24-port-switch.front.webp';
import switch48portFront from '$lib/assets/device-images/network/48-port-switch.front.webp';
import routerFirewallFront from '$lib/assets/device-images/network/1u-router-firewall.front.webp';

// Storage images
import storage1uFront from '$lib/assets/device-images/storage/1u-storage.front.webp';
import storage2uFront from '$lib/assets/device-images/storage/2u-storage.front.webp';
import storage4uFront from '$lib/assets/device-images/storage/4u-storage.front.webp';

// Power images
import ups2uFront from '$lib/assets/device-images/power/2u-ups.front.webp';

// KVM images
import consoleDrawerFront from '$lib/assets/device-images/kvm/1u-console-drawer.front.webp';

/**
 * Bundled image data structure
 */
interface BundledImageSet {
	front?: string;
	rear?: string;
}

/**
 * Map of device slugs to their bundled images
 *
 * Keys match the slugs generated by starterLibrary.ts
 * Only active devices with real images are included
 */
const BUNDLED_IMAGES: Record<string, BundledImageSet> = {
	// Servers
	'1u-server': { front: server1uFront },
	'2u-server': { front: server2uFront },
	'4u-server': { front: server4uFront },

	// Network
	'8-port-switch': { front: switch8portFront },
	'24-port-switch': { front: switch24portFront },
	'48-port-switch': { front: switch48portFront },
	'1u-router-firewall': { front: routerFirewallFront },

	// Storage
	'1u-storage': { front: storage1uFront },
	'2u-storage': { front: storage2uFront },
	'4u-storage': { front: storage4uFront },

	// Power
	'2u-ups': { front: ups2uFront },

	// KVM
	'1u-console-drawer': { front: consoleDrawerFront }
};

/**
 * Get a bundled image URL for a device slug and face
 *
 * @param slug - Device type slug (e.g., '1u-server')
 * @param face - 'front' or 'rear'
 * @returns Image URL string or undefined if no bundled image exists
 *
 * @example
 * getBundledImage('1u-server', 'front') // '/assets/server/1u-server.front.webp'
 * getBundledImage('1u-blank', 'front') // undefined (no bundled image for blanks)
 */
export function getBundledImage(slug: string, face: 'front' | 'rear'): string | undefined {
	const imageSet = BUNDLED_IMAGES[slug];
	if (!imageSet) return undefined;
	return imageSet[face];
}

/**
 * Get list of device slugs that have bundled images
 *
 * @returns Array of device slug strings
 *
 * @example
 * getBundledImageSlugs() // ['1u-server', '2u-server', ...]
 */
export function getBundledImageSlugs(): string[] {
	return Object.keys(BUNDLED_IMAGES);
}

/**
 * Check if a device slug has a bundled image
 *
 * @param slug - Device type slug
 * @returns true if device has at least one bundled image
 */
export function hasBundledImage(slug: string): boolean {
	return slug in BUNDLED_IMAGES;
}
